### ISSUE TITLE
why I get this error

### ISSUE THREAD

**Issue by mbwyjr** [atcelen/IDesign#4]
Traceback (most recent call last):
  File "/mnt/second_drive/user_data/xqy/IDesign/main.py", line 10, in <module>
    i_design.correct_design()
  File "/mnt/second_drive/user_data/xqy/IDesign/IDesign.py", line 133, in correct_design
    user_proxy.initiate_chat(
  File "/mnt/second_drive/user_data/xqy/.conda/envs/idesign/lib/python3.9/site-packages/autogen/agentchat/conversable_agent.py", line 550, in initiate_chat
    self.send(self.generate_init_message(**context), recipient, silent=silent)
  File "/mnt/second_drive/user_data/xqy/.conda/envs/idesign/lib/python3.9/site-packages/autogen/agentchat/conversable_agent.py", line 348, in send
    recipient.receive(message, self, request_reply, silent)
  File "/mnt/second_drive/user_data/xqy/.conda/envs/idesign/lib/python3.9/site-packages/autogen/agentchat/conversable_agent.py", line 481, in receive
    reply = self.generate_reply(messages=self.chat_messages[sender], sender=sender)
  File "/mnt/second_drive/user_data/xqy/.conda/envs/idesign/lib/python3.9/site-packages/autogen/agentchat/conversable_agent.py", line 906, in generate_reply
    final, reply = reply_func(self, messages=messages, sender=sender, config=reply_func_tuple["config"])
  File "/mnt/second_drive/user_data/xqy/.conda/envs/idesign/lib/python3.9/site-packages/autogen/agentchat/groupchat.py", line 271, in run_chat
    reply = speaker.generate_reply(sender=self)
  File "/mnt/second_drive/user_data/xqy/.conda/envs/idesign/lib/python3.9/site-packages/autogen/agentchat/conversable_agent.py", line 906, in generate_reply
    final, reply = reply_func(self, messages=messages, sender=sender, config=reply_func_tuple["config"])
  File "/mnt/second_drive/user_data/xqy/.conda/envs/idesign/lib/python3.9/site-packages/autogen/agentchat/conversable_agent.py", line 733, in check_termination_and_human_reply
    reply = self.get_human_input(
  File "/mnt/second_drive/user_data/xqy/IDesign/corrector_agents.py", line 24, in get_human_input
    match = re.search(pattern, message["content"], re.DOTALL).group(1)
AttributeError: 'NoneType' object has no attribute 'group'

**Comment by Mingze2379** [comment]
Same issue. How did you fix it?
